version: '3.7'
networks:
  mongo-net:
    name: mongo-net
services:
  mongo-2.mongo:
    hostname: mongo-2.mongo
    container_name: mongo-2.mongo
    image: mongo:4.4.4-bionic
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
      - "37018:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/file.key:/data/file.key"
      - ./mongo-rs0-2/data:/data/db

  mongo-1.mongo:
    hostname: mongo-1.mongo
    container_name: mongo-1.mongo
    image: mongo:4.4.4-bionic
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
    - "37019:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/file.key:/data/file.key"
      - ./mongo-rs0-1/data:/data/db

  mongo-0.mongo:
    hostname: mongo-0.mongo
    container_name: mongo-0.mongo
    image: mongo:4.4.4-bionic
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all"
    ports:
    - "37017:27017"
    links:
    - mongo-1.mongo:mongo-1.mongo
    - mongo-2.mongo:mongo-2.mongo
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/setup.sh:/scripts/setup.sh"
      - "./scripts/file.key:/data/file.key"
      - ./mongo-rs0-0/data:/data/db
