version: '3.1'
services:
  mongo-rs0-1:
    image: "start-mongo-rs"
    build: ./mongo-rs0-1
    ports:
      - "37017:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo:4.4.4-bionic"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "37018:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: "mongo:4.4.4-bionic"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "37019:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db

  setup-rs:
    image: "setup-mongo-rs"
    build: ./setup
    depends_on:
      - "mongo-rs0-1"

  # adminmongo:
  #   image: "mrvautin/adminmongo"
  #   ports:
  #     - "8192:1234"
  #   environment:
  #     - HOST=0.0.0.0
